spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

oauth:
  apple:
    clientId: adbcd
jwt:
  secret: "ToiguaOaVf3o3wD8XSnJV10MlWo0exackfAofpscMqs="
